### ISSUE TITLE
Bug when rotating screen with API 28 (PIE)

### ISSUE THREAD

**Issue by SergioDelValle** [Over17/UnityShowAndroidStatusBar#18] opened 2019-01-28 17:17 UTC
As mentioned in [THIS ](https://forum.unity.com/threads/status-bar-always-hidden-on-android.362779/page-2#post-4114585)unity forum post, there's a bug when using this plugin and rotating the screen.

I've attached a repro-project (both unity project and the Android project for the plugin)
[Status Bar Unity Test.zip](https://github.com/Over17/UnityShowAndroidStatusBar/files/2804079/Status.Bar.Unity.Test.zip)

Unity version es 2018.3.1.f1

It have been tested on Android Emulator (Nexus 5X API 26) and real device (One Plus 3, Api 26 too 8.0.0). In emulator everything works as expected with the exception of API 28, that shows weird behaviour when rotating the screen.

Also added a precompiled apk
[Status bar test.zip](https://github.com/Over17/UnityShowAndroidStatusBar/files/2804089/Status.bar.test.zip)

**Comment by Over17** [comment] 2019-02-22 10:57
I can confirm the ugly status bars on S9 and Pixel3XL (Android 9). Will see what could be done.
(the emulator may have own issues too)

**Comment by SergioDelValle** [comment] 2019-02-22 11:14
> I can confirm the ugly status bars on S9 and Pixel3XL (Android 9). Will see what could be done.
> (the emulator may have own issues too)

Thanks a lot for taking the time to look into it :)

**Comment by Over17** [comment] 2019-02-22 15:42
I've just created an empty project with the plugin and everything by default (transparent status bar), and it's working greatly on P20pro, Pixel3xl and S9. Must be an opaque status bar issue.

**Comment by elberto** [comment] 2019-02-27 09:09
I have a Fatal error too on Pie prelaunch report (Unity 2018.2.17f1 gradle build)
`FATAL EXCEPTION: main
Process: com.xxx.xxx, PID: xxx
java.lang.RuntimeException: Unable to pause activity {com.xxx.xxx/com.unity3d.nostatusbar.UnityPlayerActivityStatusBar}: java.util.ConcurrentModificationException
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4031)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.util.ConcurrentModificationException
	at i.put(:com.google.android.gms.dynamite_measurementdynamite@14799081@14.7.99 (100400-223214910):101)
	at fo.a(:com.google.android.gms.dynamite_measurementdynamite@14799081@14.7.99 (100400-223214910):44)
	at fl.onActivityPaused(:com.google.android.gms.dynamite_measurementdynamite@14799081@14.7.99 (100400-223214910):53)
	at android.app.Application.dispatchActivityPaused(Application.java:248)
	at android.app.Activity.onPause(Activity.java:1731)
	at com.unity3d.player.UnityPlayerActivity.onPause(Unknown Source:0)
	at android.app.Activity.performPause(Activity.java:7329)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnPause(MonitoringInstrumentation.java:190)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)`

**Comment by ayush-12** [comment] 2019-02-27 11:51
> I've just created an empty project with the plugin and everything by default (transparent status bar), and it's working greatly on P20pro, Pixel3xl and S9. Must be an opaque status bar issue.
I have the same issue but on S8 and android 8.0

**Comment by ayush-12** [comment] 2019-02-27 11:52
> I've just created an empty project with the plugin and everything by default (transparent status bar), and it's working greatly on P20pro, Pixel3xl and S9. Must be an opaque status bar issue.

I am getting the same issue but in S8 and Android 8.0

**Comment by Over17** [comment] 2019-05-02 11:33
I'm closing this as a duplicate of #19 .

**Closed as completed by Over17** 2019-05-02 11:33 UTC
