### ISSUE TITLE
Issue at Android 9 And Screen 1080*2131

### ISSUE THREAD

**Issue by marad747** [Over17/UnityShowAndroidStatusBar#20] opened 2019-05-14 20:41 UTC
A have phone galaxy A30 screensize = 1080*2131. I need show a top status bar. But when i import this plugin my Screen.height and Screen.width are decreased and i saw a double navigation bar. I need your help
http://prntscr.com/nolj7l

**Comment by Over17** [comment] 2019-05-15 07:40
Looks like a duplicate of #19 .

**Closed as completed by Over17** 2019-05-15 07:40 UTC
